# Generated by .github/bump-tap.sh on every tagged release. Edits here are
# overwritten; change the template in hev/factory instead.
class Factory < Formula
  desc "Orchestrate a crew of coding agents on a Mac you own"
  homepage "https://hevfactory.com"
  license "Apache-2.0"

  # Sorted the way `brew audit` sorts them, which treats the macOS constraint as
  # one more name in the list. launchd, tmux and the login keychain are why it
  # is there: no Linux build exists to fall back to.
  depends_on "gh"
  depends_on "jq"
  depends_on :macos
  depends_on "tmux"

  # Not `on_arm`/`on_intel`. Those blocks install and run, but `brew audit`
  # rejects url and sha256 inside them, and a formula that only works until
  # somebody audits it is a formula with a fuse in it.
  if Hardware::CPU.arm?
    url "https://github.com/hev/factory/releases/download/v0.1.2/factory_0.1.2_darwin_arm64.tar.gz"
    sha256 "e991111d2a63b96f90f5502dc64bb652d9b22308660d2a028c87ecd06d7d3af9"
  else
    url "https://github.com/hev/factory/releases/download/v0.1.2/factory_0.1.2_darwin_amd64.tar.gz"
    sha256 "ef12d07fef1d1e9390ec4b76d2972ec7eb0134e6b3997624349406e15f26116c"
  end

  def install
    bin.install "factory"
  end

  def caveats
    <<~EOS
      A factory runs agents in yolo mode, as you, on this machine. Read the
      warning before the first run: https://github.com/hev/factory

      You still need `claude`, logged in. Homebrew cannot install it, and the
      factory ships no model and never sees your API keys.

      The contracts a factory reads are a git checkout you own and edit by
      commit, not files under this prefix. `factory` clones them on first run
      and records the path in ~/.factory/root.

      Run `factory` to start.
    EOS
  end

  test do
    assert_match "factory", shell_output("#{bin}/factory --help")
  end
end
