# Generated by .github/bump-tap.sh on every tagged release. Edits here are
# overwritten; change the template in hev/factory instead.
class Factory < Formula
  desc "Orchestrate a crew of coding agents on a Mac you own"
  homepage "https://hevfactory.com"
  license "Apache-2.0"

  # Sorted the way `brew audit` sorts them, which treats the macOS constraint as
  # one more name in the list. launchd, tmux and the login keychain are why it
  # is there: no Linux build exists to fall back to.
  depends_on "gh"
  depends_on "jq"
  depends_on :macos
  depends_on "tmux"

  # Not `on_arm`/`on_intel`. Those blocks install and run, but `brew audit`
  # rejects url and sha256 inside them, and a formula that only works until
  # somebody audits it is a formula with a fuse in it.
  if Hardware::CPU.arm?
    url "https://github.com/hev/factory/releases/download/v0.1.1/factory_0.1.1_darwin_arm64.tar.gz"
    sha256 "27319afb615938df5aee5974db854c8e3dd7f8d496fd7c3b3bbb0deb75dbbbdf"
  else
    url "https://github.com/hev/factory/releases/download/v0.1.1/factory_0.1.1_darwin_amd64.tar.gz"
    sha256 "3fce8cfaa2570dd6bc71a473c5de31a79fe3dc17a09cbb8f94504f3404fe7338"
  end

  def install
    bin.install "factory"
  end

  def caveats
    <<~EOS
      A factory runs agents in yolo mode, as you, on this machine. Read the
      warning before the first run: https://github.com/hev/factory

      You still need `claude`, logged in. Homebrew cannot install it, and the
      factory ships no model and never sees your API keys.

      The contracts a factory reads are a git checkout you own and edit by
      commit, not files under this prefix. `factory` clones them on first run
      and records the path in ~/.factory/root.

      Run `factory` to start.
    EOS
  end

  test do
    assert_match "factory", shell_output("#{bin}/factory --help")
  end
end
