# Generated by .github/bump-tap.sh on every tagged release. Edits here are
# overwritten; change the template in hev/factory instead.
class Factory < Formula
  desc "Orchestrate a crew of coding agents on a Mac you own"
  homepage "https://hevfactory.com"
  version "0.1.0"
  license "Apache-2.0"

  # launchd, tmux and the login keychain. There is no Linux build to fall back
  # to, so this says so rather than failing at run time.
  depends_on :macos

  depends_on "gh"
  depends_on "jq"
  depends_on "tmux"

  on_arm do
    url "https://github.com/hev/factory/releases/download/v0.1.0/factory_0.1.0_darwin_arm64.tar.gz"
    sha256 "5b9afdc725b41b1c2973c2dbeec6f284dbd989ad4978d953cd0223aba5300c2f"
  end

  on_intel do
    url "https://github.com/hev/factory/releases/download/v0.1.0/factory_0.1.0_darwin_amd64.tar.gz"
    sha256 "b846d0c8c73ca5a98f3e4ccc6a54930808d79c4d77490329a540e34fc4a8ccf7"
  end

  def install
    bin.install "factory"
  end

  def caveats
    <<~EOS
      A factory runs agents in yolo mode, as you, on this machine. Read the
      warning before the first run: https://github.com/hev/factory

      You still need `claude`, logged in. Homebrew cannot install it, and the
      factory ships no model and never sees your API keys.

      The contracts a factory reads are a git checkout you own and edit by
      commit, not files under this prefix. `factory` clones them on first run
      and records the path in ~/.factory/root.

      Run `factory` to start.
    EOS
  end

  test do
    assert_match "factory", shell_output("#{bin}/factory --help")
  end
end