# Generated by .github/bump-tap.sh on every tagged release. Edits here are
# overwritten; change the template in hev/kit instead.
class Kit < Formula
  desc "Hybrid search over your coding agent traces, built on turbopuffer and hev layer"
  homepage "https://hev.dev/kit"
  license "Apache-2.0"

  # The capture daemon runs under launchd; there is no Linux build to fall
  # back to.
  depends_on :macos

  # Not `on_arm`/`on_intel`. Those blocks install and run, but `brew audit`
  # rejects url and sha256 inside them.
  if Hardware::CPU.arm?
    url "https://github.com/hev/kit/releases/download/v0.3.1/kit_0.3.1_darwin_arm64.tar.gz"
    sha256 "5d38decd0ee65871e07c343b55911fcedba10e0d32cd7eead29b85c9d6b9299c"
  else
    url "https://github.com/hev/kit/releases/download/v0.3.1/kit_0.3.1_darwin_amd64.tar.gz"
    sha256 "42576d1f586075c0fe303b2a2f5b135aa74c2e0b0e7a345c0b34dbe08ec77583"
  end

  def install
    bin.install "hev"
  end

  def caveats
    <<~EOS
      `hev up` runs the hev layer gateway and the kit dashboard in Docker and
      installs the capture daemon under launchd. It needs Docker running and a
      turbopuffer API key (https://turbopuffer.com/dashboard):

        export TURBOPUFFER_API_KEY=tpuf_...
        hev up

      Your transcripts are archived, as they are, to a namespace in your own
      turbopuffer account. They can hold secrets, and kit does not redact them
      yet: https://hev.dev/kit/#sensitive

      `hev down` stops everything and leaves the archive in place.

      After `brew upgrade hev/tap/kit`, run `hev up` again: it restarts the
      daemon on the new binary and moves the dashboard and gateway to the
      images that release pins.
    EOS
  end

  test do
    assert_match "hev kit", shell_output("#{bin}/hev --help")
  end
end
