# Generated by .github/bump-tap.sh on every tagged release. Edits here are
# overwritten; change the template in hev/kit instead.
class Kit < Formula
  desc "Keep your coding-agent transcripts searchable in a store you control"
  homepage "https://hev.dev/kit"
  license "Apache-2.0"

  # The capture daemon runs under launchd; there is no Linux build to fall
  # back to.
  depends_on :macos

  # Not `on_arm`/`on_intel`. Those blocks install and run, but `brew audit`
  # rejects url and sha256 inside them.
  if Hardware::CPU.arm?
    url "https://github.com/hev/kit/releases/download/v0.1.0/kit_0.1.0_darwin_arm64.tar.gz"
    sha256 "ca06ec5084ca35e2560a8f6b4a552891c99fcae96a383dfb21f273014ba275bf"
  else
    url "https://github.com/hev/kit/releases/download/v0.1.0/kit_0.1.0_darwin_amd64.tar.gz"
    sha256 "e0ea3b229bf6f15fba69acc646449c1f4d3f08fae2939fdafc2b3b4aa2c4a095"
  end

  def install
    bin.install "hev"
  end

  def caveats
    <<~EOS
      `hev up` runs the hev layer gateway and the kit dashboard in Docker and
      installs the capture daemon under launchd. It needs Docker running and a
      turbopuffer API key (https://turbopuffer.com/dashboard):

        export TURBOPUFFER_API_KEY=tpuf_...
        hev up

      Your transcripts are archived, as they are, to a namespace in your own
      turbopuffer account. They can hold secrets, and kit does not redact them
      yet: https://github.com/hev/kit#before-you-run-it-sensitive-data

      `hev down` stops everything and leaves the archive in place.

      After `brew upgrade kit`, run `hev up` again: it restarts the daemon on
      the new binary and moves the dashboard to the matching image.
    EOS
  end

  test do
    assert_match "hev kit", shell_output("#{bin}/hev --help")
  end
end
