# Generated by .github/bump-tap.sh on every tagged release. Edits here are
# overwritten; change the template in hev/kit instead.
class Kit < Formula
  desc "Hybrid search over your coding agent traces, built on turbopuffer and hev layer"
  homepage "https://hev.dev/kit"
  license "Apache-2.0"

  # The capture daemon runs under launchd; there is no Linux build to fall
  # back to.
  depends_on :macos

  # Not `on_arm`/`on_intel`. Those blocks install and run, but `brew audit`
  # rejects url and sha256 inside them.
  if Hardware::CPU.arm?
    url "https://github.com/hev/kit/releases/download/v0.1.1/kit_0.1.1_darwin_arm64.tar.gz"
    sha256 "3703f58e954d5525fb60866a96424d46009e15fec7fa28be05ea8aa9d99cf7fa"
  else
    url "https://github.com/hev/kit/releases/download/v0.1.1/kit_0.1.1_darwin_amd64.tar.gz"
    sha256 "d13041721225b9cd46fec435ad9abd4112f1f82434235392fc24f3a0816ad298"
  end

  def install
    bin.install "hev"
  end

  def caveats
    <<~EOS
      `hev up` runs the hev layer gateway and the kit dashboard in Docker and
      installs the capture daemon under launchd. It needs Docker running and a
      turbopuffer API key (https://turbopuffer.com/dashboard):

        export TURBOPUFFER_API_KEY=tpuf_...
        hev up

      Your transcripts are archived, as they are, to a namespace in your own
      turbopuffer account. They can hold secrets, and kit does not redact them
      yet: https://hev.dev/kit/#sensitive

      `hev down` stops everything and leaves the archive in place.

      After `brew upgrade kit`, run `hev up` again: it restarts the daemon on
      the new binary and moves the dashboard to the matching image.
    EOS
  end

  test do
    assert_match "hev kit", shell_output("#{bin}/hev --help")
  end
end
